### ISSUE TITLE
为什么都配置好了，numbytes=recv(sockfd, buf, MAXDATASIZE-1, 0)) > 0一直没消息呢

### ISSUE THREAD

**Issue by ryanyej** [qinyunchuan/dgps_ros#1]
[ INFO] [1641970328.057329581]: Username= 
[ INFO] [1641970328.058037087]: password= 
GET /RTCM32_GGB HTTP/1.1
Host: rtk.ntrip.qxwz.com
User-Agent: NTRIP NtripClientPOSIX/$Revision: 1.51 $
Connection: close
Authorization: Basic cXh2dGFqMDAxOjAzZGZmYjQ=

$GNGGA,093712.30,3109.01976962,N,12110.19862088,E,2,14,0.9,19.7961,M,10.6384,M,01,3609*55

然后没有反应了呢

**Comment by ryanyej** [comment]
然后就120S超时，一条RTCM数据也没有收到

**Comment by qinyunchuan** [comment]
你是用的哪款gps设备？能否把配置参数发一下，我试试重现看看

**Comment by ryanyej** [comment]
经过调试后收到了，但是打印出来的内容都是乱码。
我用的是CUAV的RTK-9P设备。现在想通过您的程序将RTCM消息直接提取出来，赋值给mavros里的/mavros/gps_rtk/send_rtcm消息。
现在直接将ntrip回复的消息发给飞控的话，会出现ROS_FATAL("gps_rtk: RTCM message received is bigger than the maximal possible size.");
所以我的理解需要将这个消息过滤一下再赋值给/mavros/gps_rtk/send_rtcm消息。
您有这方面的经验吗

**Comment by qinyunchuan** [comment]
项目没有实现send_rtcm消息，是直接送到模块里的。RTK-9P好像有两个串口，你可以用其中一个串口直接输入RTCM数据进去

**Comment by Roswellii** [comment]
> 经过调试后收到了，但是打印出来的内容都是乱码。 我用的是CUAV的RTK-9P设备。现在想通过您的程序将RTCM消息直接提取出来，赋值给mavros里的/mavros/gps_rtk/send_rtcm消息。 现在直接将ntrip回复的消息发给飞控的话，会出现ROS_FATAL("gps_rtk: RTCM message received is bigger than the maximal possible size."); 所以我的理解需要将这个消息过滤一下再赋值给/mavros/gps_rtk/send_rtcm消息。 您有这方面的经验吗

您好，我也遇到了输出$GNGGA,093712.30,3109.01976962,N,12110.19862088,E,2,14,0.9,19.7961,M,10.6384,M,01,3609*55后没有反应的问题，请问您如何进行调试的？

**Comment by qinyunchuan** [comment]
请先看看这个设备串口有没有GNGGA消息输出

**Comment by Roswellii** [comment]
谢谢！发现是命令识别码有些不同，输出的是另一个类型的消息，改过来就好啦。

发件人: ***@***.***>
发送时间: 2022年12月16日 14:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [qinyunchuan/dgps_ros] 为什么都配置好了，numbytes=recv(sockfd, buf, MAXDATASIZE-1, 0)) > 0一直没消息呢 (Issue #1)


请先看看这个设备串口有没有GNGGA消息输出

―
